// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBizVsSnzYd1BjILLGRqynSWzdnJ64Akuo',
    appId: '1:40943868993:web:726dbe9e58a6b64eaffac0',
    messagingSenderId: '40943868993',
    projectId: 'budgettracker-0524',
    authDomain: 'budgettracker-0524.firebaseapp.com',
    storageBucket: 'budgettracker-0524.appspot.com',
    measurementId: 'G-MP7R0T5K2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPcdScEX_ASz7abKOqW1DtNCZr0k-3Ex8',
    appId: '1:40943868993:android:f5e6602a8811a784affac0',
    messagingSenderId: '40943868993',
    projectId: 'budgettracker-0524',
    storageBucket: 'budgettracker-0524.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZPODQAflSPMYBYX4W3flBkVHoZ-zsm8Y',
    appId: '1:40943868993:ios:e9231f949983b8feaffac0',
    messagingSenderId: '40943868993',
    projectId: 'budgettracker-0524',
    storageBucket: 'budgettracker-0524.appspot.com',
    iosBundleId: 'com.example.budgetTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZPODQAflSPMYBYX4W3flBkVHoZ-zsm8Y',
    appId: '1:40943868993:ios:2877442c8d27fa51affac0',
    messagingSenderId: '40943868993',
    projectId: 'budgettracker-0524',
    storageBucket: 'budgettracker-0524.appspot.com',
    iosBundleId: 'com.example.budgetTracker.RunnerTests',
  );
}
